/**
 * Generates a self-contained Jupyter notebook (nbformat 4.5) that reproduces
 * a computation done in the web app, with explanatory markdown. Running the
 * notebook locally yields the same data as the app (same SpinWaveToolkit
 * version, same SI inputs).
 */
import { getModel } from '../models/registry';
import { getMaterialPreset } from '../models/materials';
import { SWT_CITATION, SWT_CITATION_BIBTEX, SWT_CITATION_TEXT } from '../models/citation';
import type { ComputeJob, MaterialValues, ModelId, QuantityDef } from '../models/types';

export interface NotebookInput {
  modelId: ModelId;
  materialPresetId: string;
  material: MaterialValues;
  materialPresetId2?: string;
  material2?: MaterialValues;
  job: ComputeJob;
  paramsDisplay: Record<string, string>;
  swtVersion: string | null;
}

interface NbCell {
  cell_type: 'markdown' | 'code';
  id: string;
  metadata: Record<string, never>;
  source: string[];
  outputs?: never[];
  execution_count?: null;
}

let cellCounter = 0;

function toLines(text: string): string[] {
  const lines = text.split('\n');
  return lines.map((l, i) => (i < lines.length - 1 ? l + '\n' : l)).filter((l) => l !== '');
}

function md(text: string): NbCell {
  return { cell_type: 'markdown', id: `cell-${cellCounter++}`, metadata: {}, source: toLines(text) };
}

function code(text: string): NbCell {
  return {
    cell_type: 'code',
    id: `cell-${cellCounter++}`,
    metadata: {},
    source: toLines(text),
    outputs: [],
    execution_count: null,
  };
}

/** Format a JS value as a Python literal. */
function py(value: number | string | null): string {
  if (value === null) return 'None';
  if (value === 'inf') return 'np.inf';
  if (typeof value === 'string') return `"${value}"`;
  if (Number.isInteger(value) && Math.abs(value) < 1e15) return String(value);
  return String(value);
}

function pyKwargs(obj: Record<string, number | string> | undefined): string {
  if (!obj) return '';
  return Object.entries(obj)
    .map(([k, v]) => `${k}=${py(v)}`)
    .join(', ');
}

function conversionSuffix(q: QuantityDef): string {
  if (q.nbConvert) return q.nbConvert;
  if (q.scale === 1) return '';
  return ` * ${q.scale}  # -> ${q.unit}`;
}

function materialCode(
  varName: string,
  presetId: string,
  values: MaterialValues,
): string {
  const preset = getMaterialPreset(presetId);
  if (preset.swtName) {
    return `${varName} = SWT.${preset.swtName}  # predefined material`;
  }
  return [
    `${varName} = SWT.Material(`,
    `    Ms=${py(values.Ms)},        # saturation magnetization (A/m)`,
    `    Aex=${py(values.Aex)},      # exchange stiffness (J/m)`,
    `    alpha=${py(values.alpha)},  # Gilbert damping`,
    `    gamma=${py(values.gamma)},  # gyromagnetic ratio (rad*Hz/T)`,
    `    mu0dH0=${py(values.mu0dH0)},  # inhomogeneous broadening (T)`,
    `    Ku=${py(values.Ku)},        # surface anisotropy (J/m^2)`,
    `)`,
  ].join('\n');
}

export function generateNotebook(input: NotebookInput): string {
  cellCounter = 0;
  const model = getModel(input.modelId);
  const { job } = input;
  const quantities = model.quantities.filter((q) => job.quantities.some((jq) => jq.id === q.id));

  const isPolariton = input.modelId === 'BulkPolariton';
  const kFactor = isPolariton ? '1' : '1e-6';
  const kLabel = isPolariton ? 'Wavenumber k (rad/m)' : 'Wavenumber k (rad/µm)';
  const kExpr = isPolariton ? 'kxi' : 'kxi * 1e-6';

  const cells: NbCell[] = [];

  // --- Title & parameters -------------------------------------------------
  const paramTable = Object.entries(input.paramsDisplay)
    .map(([k, v]) => `| ${k} | ${v} |`)
    .join('\n');
  cells.push(
    md(
      `# ${model.label} — SpinWaveToolkit calculation

${model.info.summary}

This notebook was generated by [SpinWaveToolkit Web](https://github.com/CEITECmagnonics/SpinWaveToolkit) on ${new Date().toISOString().slice(0, 10)} and reproduces the calculation performed in the browser (SpinWaveToolkit ${input.swtVersion ?? '1.3.0'}).

**Parameters**

| Parameter | Value |
|---|---|
| Material | ${getMaterialPreset(input.materialPresetId).label} |
${input.materialPresetId2 ? `| Material (layer 2) | ${getMaterialPreset(input.materialPresetId2).label} |\n` : ''}${paramTable}`,
    ),
  );

  // --- Install & imports ---------------------------------------------------
  cells.push(
    code(`# Install SpinWaveToolkit (pinned to the version used by the web app)
%pip install --quiet SpinWaveToolkit==${input.swtVersion ?? '1.3.0'} matplotlib`),
  );
  cells.push(
    code(`import numpy as np
import matplotlib.pyplot as plt
import SpinWaveToolkit as SWT`),
  );

  // --- Material(s) ----------------------------------------------------------
  let matCell = materialCode('material', input.materialPresetId, input.material);
  if (model.hasSecondMaterial && input.material2 && input.materialPresetId2) {
    matCell += '\n' + materialCode('material2', input.materialPresetId2, input.material2);
  }
  cells.push(code(matCell));

  // --- k vector & model construction ----------------------------------------
  const k = job.kRange;
  const kFn = k.spacing === 'log' ? 'np.geomspace' : 'np.linspace';
  const ctorArgs: string[] = ['material=material', 'kxi=kxi'];
  for (const [key, value] of Object.entries(job.params)) {
    if (key === 'material2') continue;
    const def = model.params.find((p) => p.key === key);
    const display = def ? input.paramsDisplay[def.label] : undefined;
    ctorArgs.push(`${key}=${py(value)}${display ? `,  # ${display}` : ','}`);
  }
  if (model.hasSecondMaterial && input.material2) ctorArgs.push('material2=material2,');

  cells.push(
    code(`# Wavevector range (SI units: rad/m)
kxi = ${kFn}(${py(k.min)}, ${py(k.max)}, ${k.points})

model = SWT.${model.id}(
    ${ctorArgs.map((a) => (a.endsWith(',') ? a : a + ',')).join('\n    ')}
)`),
  );

  // --- Quantities ------------------------------------------------------------
  const methodKwargs = pyKwargs(job.methodKwargs);
  for (const q of quantities) {
    cells.push(...quantityCells(q, job, methodKwargs, { kExpr, kFactor, kLabel }));
  }

  // --- Physics explanation ----------------------------------------------------
  const formulas = (model.info.formulas ?? [])
    .map((f) => `$$${f.latex}$$\n\n*${f.caption}*`)
    .join('\n\n');
  const refs = model.info.references.map((r) => `- [${r.label}](${r.url})`).join('\n');
  cells.push(
    md(
      `## About this calculation

${model.info.details.join('\n\n')}

${formulas ? formulas + '\n\n' : ''}**Model references**

${refs}

## How to cite

If you use SpinWaveToolkit in your work, please cite the package paper:

> ${SWT_CITATION_TEXT}

DOI: [${SWT_CITATION.doi}](${SWT_CITATION.url}) · Repository: [CEITECmagnonics/SpinWaveToolkit](https://github.com/CEITECmagnonics/SpinWaveToolkit)

\`\`\`bibtex
${SWT_CITATION_BIBTEX}
\`\`\``,
    ),
  );

  const notebook = {
    cells,
    metadata: {
      kernelspec: { display_name: 'Python 3', language: 'python', name: 'python3' },
      language_info: { name: 'python', version: '3' },
    },
    nbformat: 4,
    nbformat_minor: 5,
  };
  return JSON.stringify(notebook, null, 1);
}

function quantityCells(
  q: QuantityDef,
  job: ComputeJob,
  methodKwargs: string,
  kAxis: { kExpr: string; kFactor: string; kLabel: string },
): NbCell[] {
  const jq = job.quantities.find((x) => x.id === q.id)!;
  const conv = conversionSuffix(q);
  const kw = jq.kwargNames
    ? pyKwargs(
        Object.fromEntries(
          Object.entries(job.methodKwargs ?? {}).filter(([k]) => jq.kwargNames!.includes(k)),
        ),
      )
    : '';
  void methodKwargs;

  const plotFooter = (yLabel: string, title: string, legend = true) =>
    `ax.set_xlabel("${kAxis.kLabel}")
ax.set_ylabel("${yLabel}")
${legend ? 'ax.legend()\n' : ''}ax.set_title("${title}")
plt.show()`;

  switch (q.returns) {
    case 'array': {
      if (jq.modeArg === 'n_nT') {
        return [
          code(`# ${q.label}
fig, ax = plt.subplots()
for n in ${JSON.stringify(job.modes)}:
    y = model.${q.method}(n=n, nT=${job.nT})${conv}
    ax.plot(${kAxis.kExpr}, y, label=f"n={n}")
${plotFooter(q.axisLabel, q.label)}`),
        ];
      }
      if (jq.modeArg === 'n') {
        return [
          code(`# ${q.label}
fig, ax = plt.subplots()
for n in ${JSON.stringify(job.modes)}:
    y = model.${q.method}(n=n)${conv}
    ax.plot(${kAxis.kExpr}, y, label=f"mode {n}")
${plotFooter(q.axisLabel, q.label)}`),
        ];
      }
      return [
        code(`# ${q.label}
y = model.${q.method}(${kw})${conv}
fig, ax = plt.subplots()
ax.plot(${kAxis.kExpr}, y)
${plotFooter(q.axisLabel, q.label, false)}`),
      ];
    }

    case 'stacked':
    case 'tuple_stacked': {
      const unpack =
        q.returns === 'tuple_stacked'
          ? `freqs, profiles = model.${q.method}()  # frequencies + mode profiles`
          : `freqs = model.${q.method}()`;
      const labels = q.stackedLabels
        ? `labels = ${JSON.stringify(q.stackedLabels)}`
        : `labels = [f"mode {i}" for i in range(len(freqs))]`;
      return [
        code(`# ${q.label}
${unpack}
${labels}
fig, ax = plt.subplots()
for i, row in enumerate(np.atleast_2d(freqs)):
    y = row${conv}
    ax.plot(${kAxis.kExpr}, y, label=labels[i] if i < len(labels) else f"mode {i}")
${plotFooter(q.axisLabel, q.label)}`),
      ];
    }

    case 'grid': {
      const modeArgStr =
        jq.modeArg === 'n_nT'
          ? `n=${job.modes[0]}, nT=${job.nT}`
          : jq.modeArg === 'n'
            ? `n=${job.modes[0]}`
            : kw;
      return [
        code(`# ${q.label}
w, bloch = model.${q.method}(${modeArgStr})
fig, ax = plt.subplots()
pcm = ax.pcolormesh(${kAxis.kExpr}, w * 1e-9 / (2 * np.pi), bloch / np.nanmax(bloch), shading="auto", cmap="viridis")
fig.colorbar(pcm, ax=ax, label="Bloch function (normalized)")
ax.set_xlabel("${kAxis.kLabel}")
ax.set_ylabel("Frequency f (GHz)")
ax.set_title("${q.label}")
plt.show()`),
      ];
    }

    case 'scalar':
      return [
        code(`# ${q.label}
value = model.${q.method}(${kw})${conv}
print(f"${q.label}: {value:.6g} ${q.unit}")`),
      ];

    case 'tuple_scalar':
      return [
        code(`# ${q.label}
values = np.asarray(model.${q.method}(${kw}))${conv}
for i, v in enumerate(values):
    print(f"${q.label} [{i}]: {v:.6g} ${q.unit}")`),
      ];
  }
}
